using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace POP_SF7.Windows
{
    /// <summary>
    /// Interaction logic for SelectFromList.xaml
    /// </summary>

    public enum SelectFromMenuOrAddDecider { MENU, ADD }
    public enum CourseStudentDecider { STUDENT, COURSE }

    public partial class SelectFromList : Window
    {
        public SelectFromMenuOrAddDecider MenuAddDecider { get; set; }
        public CourseStudentDecider CourseStudentDecider { get; set; }

        public PaymentMenu MenuWindow { get; set; }
        public PaymentAddEdit AddEditWindow { get; set; }

        public string selectStudent = "Izaberite ucenika";
        public string selectCourse = "Izaberite kurs";

        public SelectFromList(SelectFromMenuOrAddDecider decider, CourseStudentDecider decider2, PaymentMenu menu)
        {
            InitializeComponent();

            MenuAddDecider = decider;
            CourseStudentDecider = decider2;

            MenuWindow = menu;

            setupWindow();
        }

        public SelectFromList(SelectFromMenuOrAddDecider decider, CourseStudentDecider decider2, PaymentAddEdit addEdit)
        {
            InitializeComponent();

            MenuAddDecider = decider;
            CourseStudentDecider = decider2;

            AddEditWindow = addEdit;

            setupWindow();
        }

        public void setupWindow()
        {
            if (CourseStudentDecider == CourseStudentDecider.COURSE)
            {
                description.Text = selectCourse;
                dataGrid.ItemsSource = ApplicationA.Instance.Courses;
            }
            else
            {
                description.Text = selectStudent;
                dataGrid.ItemsSource = ApplicationA.Instance.Students;
            }
        }

        private void closebtn_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }

        private void okbtn_Click(object sender, RoutedEventArgs e)
        {

        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }
    }
}
